### PR TITLE
Support attribute documentation via doc argument.

### LINKED ISSUE #59: New 'doc' arguments throw an error.
I am getting these errors when trying to generate skydoc rules at skydoc release 0.1.3. The rules themselves work fine with bazel 0.5.3 and up.

```
TypeError: string() got an unexpected keyword argument 'doc'
TypeError: label_list() got an unexpected keyword argument 'doc'
```

Should I expect these errors to go away in a release in near future, or should I remove all doc arguments from my attributes?

Thank you.

### PR DESCRIPTION
**Pull request by mboes**
Fixes #59.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by laurentlb** [comment]
Cool, thanks!
